### ISSUE TITLE
Cloning & renaming tool

### ISSUE THREAD

**Issue by ChShersh** [Holmusk/three-layer#27]
We need tool which will copy `three-layer` repository and rename all modules and directories according to provided names of new project and module prefix. 

### What should be changed?

- [x] Name of the project inside `package.yaml`
- [x] GitHub user and package name inside `package.yaml`
- [x] Name of `Lib/` folder inside `src/` to new prefix
- [x] Every module name
- [x] Every `Lib.*` import inside each module

### Specification

1. Tool takes two CLI arguments: name of new project and module prefix.
2. Should be implemented as separate executable/package inside `three-layer` repository and should clone everything from repo except tool itself.
3. New project should be buildable without errors and warnings after using the tool.
4. ★ Implement automated tests for this executable.

**Comment by arbus** [comment]
Sounds like a job for the summoner tool?

**Comment by ChShersh** [comment]
@arbus `summoner` doesn't support creating project using existing another project as template. We need to patch some things, like module names. And with `summoner` those names will be interpolated  variables. So implementing this tool for `three-layer` requires some specific text parsing and manipulation for very specific use case which I personally found hard to generalize. Because we also want from `three-layer` to be compilable and valid Haskell project since we still develop it and have things to do.

**Comment by ChShersh** [comment]
## Part 1

Should be implemented: pure function which takes content of file as a single string and new of module prefix name and changes content of this file according to new module name. The following should be changed:

1. Every module name.
2. Every import which starts with `Lib.`
3. Every reexport which reexport module started with `Lib`.

Steps to finish this task:

- [ ] Create package in separate folder inside this repository
- [ ] Add module with pure function implementation which performs this refactoring
- [ ] Changes `String` type to `Text` type in that function
- [ ] Write some test in documentation which can be easily run within `ghci`

**Comment by ChShersh** [comment]
## Part 2

This is a final part. This task should be considered done after **Part 2** if finished.

Here is set of subtasks (recommended order):

- [ ] Write function, which takes two arguments (described below). This function should copy every file and directory from given `FilePath` to new directory with new name.
    * Path to directory with `three-layer`
    * Name of new project
- [ ] Modify previous function to copy everything except directory with name `fix-point`
- [ ] Modify previous function even more to change names of `Lib.hs` file and `Lib` directory inside `src/` directory
- [ ] Apply previously written pure function to modify contents of each Haskell module inside generated directory
- [ ] Then change name of the project and GitHub user and package name inside `package.yaml`
- [ ] Finally: write executable that parses command-line arguments and uses all implemented functions

@TejasSC here is description. Please, ask any questions if something is unclear!

During this task you should use the following libraries:

* [`filepath`](http://hackage.haskell.org/package/filepath)
* [`directory`](http://hackage.haskell.org/package/directory)
* [`optparse-applicative`](http://hackage.haskell.org/package/optparse-applicative) (only for last part, this is an `Applicative` parser for command-line arguments)

**Comment by ChShersh** [comment]
Kudos to @TejasSC for finishing this issue!
